trigger:
- azure-dev-ops      # 1

variables:           # 2
  sa-frontend-image-name: 'moto88/sentiment-analysis-frontend:minkube'
  sa-web-app-image-name: 'moto88/sentiment-analysis-web-app:latest'
  sa-logic-image-name: 'moto88/sentiment-analysis-logic:latest'
  sa-feedback-image-name: 'rinormaloku/sentiment-analysis-feedback:latest'

jobs:                # 3
- job: SA_Frontend   # 3.a
  steps:             # 4
  - script: docker login -u $(dockerId) -p $(password)
    displayName: 'docker login'
  - script: docker build -f ./sa-frontend/Dockerfile -t $(sa-frontend-image-name) ./sa-frontend
    displayName: 'docker build frontend'
  - script: docker push $(sa-frontend-image-name) 
    displayName: 'docker push frontend'

- job: SA_WebApp     # 3.b
  steps:
  - script: docker login -u $(dockerId) -p $(password)
    displayName: 'docker login'
  - script: docker build -f ./sa-webapp/Dockerfile -t $(sa-web-app-image-name) ./sa-webapp
    displayName: 'docker build webapp'
  - script: docker push $(sa-web-app-image-name) 
    displayName: 'docker push webapp'

- job: SA_Logic
  steps:
  - script: docker login -u $(dockerId) -p $(password)
    displayName: 'docker login'
  - script: docker build -f ./sa-logic/Dockerfile -t $(sa-logic-image-name) ./sa-logic
    displayName: 'docker build logic'
  - script: docker push $(sa-logic-image-name) 
    displayName: 'docker push logic'

- job: SA_Feedback
  steps:
  - script: docker login -u $(dockerId) -p $(password)
    displayName: 'docker login'
  - script: docker build -f ./sa-feedback/Dockerfile -t $(sa-feedback-image-name) ./sa-feedback
    displayName: 'docker build feedback'
  - script: docker push $(sa-feedback-image-name) 
    displayName: 'docker push feedback'

- job: Publish_Artifacts
  steps:
  - bash: find resource-manifests -type f -name "*.yaml" -print0 | xargs -0 sed -i -e "s/{{TAG}}/$(build.buildId)/" -e "s/{{DOCKER_USER}}/$(dockerId)/"
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/resource-manifests'
      artifactName: resource-manifests